import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import ClientLayout from "./clientlayout";
import Footer from "../components/footer/footer";
import { ThemeProvider } from 'next-themes';
import { SpeedInsights } from "@vercel/speed-insights/next"


//const inter = Inter({ subsets: ["arial"] });
const inter = localFont({ src: "../fonts/Inter-Regular.ttf", display: 'swap', variable: '--font-inter' });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    
    <html lang="en" suppressHydrationWarning>
      
      <body className={inter.className}>
         <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <ClientLayout> 
          {children}
          <SpeedInsights />
        </ClientLayout>
        <Footer/>
      </ThemeProvider>
    </body>
    </html>
  );
}