import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientLayout from "./clientlayout";
import Footer from "../components/footer/footer";
import { ThemeProvider } from 'next-themes';
import { SpeedInsights } from "@vercel/speed-insights/next"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    
    <html lang="en" suppressHydrationWarning>
      
      <body className={inter.className}>
         <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <ClientLayout> </ClientLayout>
          {children}
          <SpeedInsights />
      
            <Footer/>

      </ThemeProvider>
    </body>
    </html>
  );
}