import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from 'next-themes';
import Navbar from "../components/navbar";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html 
      className="" 
      lang="en" 
      suppressHydrationWarning 
      data-scroll-behavior="smooth"
    >
      <body className={`${inter.className} flex flex-col min-h-screen bg-white dark:bg-gradient-to-b dark:from-gray-900 dark:via-slate-950 dark:to-gray-950`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          <main className="flex-grow">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}

